// SPDX-License-Identifier: (MIT OR Apache-2.0)

//! Bakes the C runtime sources into the binary.
//!
//! A released `rask` is a single file with no repo around it, so the on-disk
//! search in `find_runtime_dir` finds nothing and every native compile fails at
//! link. The sources travel inside the binary instead, and get written to a
//! cache directory the first time one is needed.
//!
//! The list is read from the directory, never written down — a hand-maintained
//! listing is what made #1041, where a source added to the tree wasn't added to
//! the constant and every binary built in between linked a `string.c` calling
//! into a file it had never heard of.

use std::path::{Path, PathBuf};

fn main() {
    let runtime_dir = runtime_dir();
    println!("cargo:rerun-if-changed={}", runtime_dir.display());

    let mut sources: Vec<PathBuf> = std::fs::read_dir(&runtime_dir)
        .unwrap_or_else(|e| panic!("cannot read runtime dir {}: {e}", runtime_dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| matches!(p.extension().and_then(|s| s.to_str()), Some("c") | Some("h")))
        .collect();
    sources.sort();

    if sources.is_empty() {
        panic!("no runtime sources in {} — runtime is incomplete", runtime_dir.display());
    }

    let mut out = String::from(
        "// @generated by build.rs — the runtime sources, keyed by file name.\n\
         pub static EMBEDDED_RUNTIME: &[(&str, &str)] = &[\n",
    );
    for path in &sources {
        // Rebuild when a source's contents change, not just when the directory
        // gains or loses an entry.
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path.file_name().unwrap().to_str().unwrap();
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_runtime.rs");
    std::fs::write(&dest, out).expect("write embedded_runtime.rs");
}

/// The runtime lives at `compiler/runtime`, four levels up from this crate.
/// `RASK_RUNTIME_DIR` overrides it so a build can point at a runtime elsewhere.
fn runtime_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("RASK_RUNTIME_DIR") {
        let p = PathBuf::from(dir);
        if p.join("runtime.c").exists() {
            return p;
        }
        panic!("RASK_RUNTIME_DIR is set but has no runtime.c");
    }

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let candidate = Path::new(&manifest).join("../../runtime");
    if candidate.join("runtime.c").exists() {
        return candidate;
    }
    panic!("no runtime next to {} — expected ../../runtime", manifest.display());
}
