// SPDX-License-Identifier: (MIT OR Apache-2.0)
//! Error code registry.
//!
//! Maps error codes (E0001, E0308, etc.) to titles, categories, and explanations.
//! Used by `rask explain <code>` and for error display.

use std::collections::HashMap;

/// Registry of all known error codes.
pub struct ErrorCodeRegistry {
    codes: HashMap<&'static str, ErrorCodeInfo>,
}

/// Information about a single error code.
pub struct ErrorCodeInfo {
    pub code: &'static str,
    pub title: &'static str,
    pub category: ErrorCategory,
    pub description: &'static str,
    pub example: &'static str,
}

/// Error category for grouping.
#[derive(Debug, Clone, Copy)]
pub enum ErrorCategory {
    Syntax,
    Resolution,
    Type,
    Trait,
    Ownership,
}

impl std::fmt::Display for ErrorCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ErrorCategory::Syntax => write!(f, "Syntax"),
            ErrorCategory::Resolution => write!(f, "Resolution"),
            ErrorCategory::Type => write!(f, "Type"),
            ErrorCategory::Trait => write!(f, "Trait"),
            ErrorCategory::Ownership => write!(f, "Ownership"),
        }
    }
}

macro_rules! register_codes {
    ($($code:literal => ($title:literal, $cat:expr, $desc:literal, $example:literal)),* $(,)?) => {{
        let mut map = HashMap::new();
        $(
            map.insert($code, ErrorCodeInfo {
                code: $code,
                title: $title,
                category: $cat,
                description: $desc,
                example: $example,
            });
        )*
        map
    }};
}

impl Default for ErrorCodeRegistry {
    fn default() -> Self {
        use ErrorCategory::*;

        Self {
            codes: register_codes! {
                // Lexer errors (E00xx)
                "E0001" => ("unexpected character", Syntax,
                    "The lexer encountered a character that isn't valid in Rask source code. This usually means a stray special character or encoding issue.",
                    "// Error: unexpected '@' (outside attribute position)\nlet x = @value"),
                "E0002" => ("unterminated string literal", Syntax,
                    "A string was opened with `\"` but never closed. Every string literal must have a matching closing quote on the same line.",
                    "// Error: string never closed\nlet msg = \"hello world"),
                "E0003" => ("invalid escape sequence", Syntax,
                    "A backslash in a string was followed by a character that isn't a recognized escape. Valid escapes: \\n, \\t, \\r, \\\\, \\\", \\0.",
                    "// Error: \\q is not a valid escape\nlet s = \"path\\qname\""),
                "E0004" => ("invalid number format", Syntax,
                    "A numeric literal has an invalid format — perhaps a suffix typo, multiple dots, or an invalid digit for the base.",
                    "// Error: invalid suffix\nlet x = 42i3  // did you mean i32?"),

                // Parser errors (E01xx)
                "E0100" => ("unexpected token", Syntax,
                    "The parser encountered a token that doesn't make sense in the current context. Check for missing operators, mismatched brackets, or Rust syntax habits.",
                    "// Error: unexpected '::'\nlet x = Option::Some(1)  // use Option.Some(1)"),
                "E0101" => ("expected token not found", Syntax,
                    "The parser expected a specific token (like a closing bracket or keyword) but found something else.",
                    "// Error: expected '}'\nfunc main() {\n    println(\"hello\")\n// missing closing brace"),
                "E0102" => ("invalid syntax", Syntax,
                    "The source code doesn't match any valid Rask construct. Common causes: using Rust syntax, missing keywords, or incorrect statement structure.",
                    "// Error: use 'func' not 'fn'\nfn add(a: i32, b: i32) -> i32 { return a + b }"),

                // Resolver errors (E02xx)
                "E0200" => ("undefined symbol", Resolution,
                    "A name was used that hasn't been defined in the current scope. Check spelling, imports, and that the definition appears before use.",
                    "func main() {\n    println(value)  // error: 'value' not defined\n}"),
                "E0201" => ("duplicate definition", Resolution,
                    "Two items share the same name in the same scope. Rename one of them.",
                    "func add(a: i32) -> i32 { return a }\nfunc add(a: i32) -> i32 { return a }  // error: duplicate"),
                "E0202" => ("circular dependency", Resolution,
                    "Two or more modules depend on each other in a cycle. Break the cycle by extracting shared types into a separate module.",
                    "// a.rk imports b, b.rk imports a → cycle"),
                "E0203" => ("symbol not visible", Resolution,
                    "The symbol exists but isn't accessible from the current module. Only `public` items are visible outside their defining module.",
                    "// In module A:\nfunc helper() { }  // not public\n// In module B:\nA.helper()  // error: not visible"),
                "E0204" => ("break outside of loop", Resolution,
                    "`break` (or `deliver`) can only appear inside a loop body (while, for, loop). It cannot be used in functions or top-level code.",
                    "func main() {\n    break  // error: not in a loop\n}"),
                "E0205" => ("continue outside of loop", Resolution,
                    "`continue` can only appear inside a loop body. It skips to the next iteration.",
                    "func main() {\n    continue  // error: not in a loop\n}"),
                "E0206" => ("return outside of function", Resolution,
                    "`return` can only appear inside a function body. It cannot be used at the top level.",
                    "return 42  // error: not in a function"),
                "E0207" => ("unknown package", Resolution,
                    "An import references a package that can't be found. Check the package name and that it's listed as a dependency.",
                    "import unknown_pkg  // error: package not found"),
                "E0208" => ("shadows import", Resolution,
                    "A local definition has the same name as an imported symbol. This can cause confusion. Rename the local or use an import alias.",
                    "import math\nlet math = 42  // error: shadows import"),
                "E0209" => ("shadows built-in", Resolution,
                    "A definition has the same name as a built-in type or function. This can cause confusing errors later. Choose a different name.",
                    "struct Vec { }  // error: shadows built-in Vec"),
                "E0210" => ("unknown break target", Resolution,
                    "`break x` means one of two things: break out with the value in `x`, or jump to the loop labelled `x`. This name is neither — no variable `x` is in scope and no enclosing loop carries that label.",
                    "outer: loop {\n    break outr  // error: did you mean the label `outer`?\n}"),

                // Type errors (E03xx)
                "E0308" => ("mismatched types", Type,
                    "An expression has a different type than what was expected. This is the most common type error — check that return types, assignments, and function arguments match.",
                    "func double(x: i32) -> i32 {\n    return \"hello\"  // error: expected i32, found string\n}"),
                "E0309" => ("undefined type", Type,
                    "A type annotation references a type that doesn't exist. Check spelling and imports.",
                    "func f(x: Strng) { }  // error: did you mean 'string'?"),
                "E0310" => ("arity mismatch", Type,
                    "A function was called with the wrong number of arguments. Check the function signature.",
                    "func add(a: i32, b: i32) -> i32 { return a + b }\nadd(1)  // error: expected 2 args, found 1"),
                "E0311" => ("type is not callable", Type,
                    "You tried to call something that isn't a function or closure. Only functions, closures, and constructors support `()` syntax.",
                    "let x = 42\nx()  // error: i64 is not callable"),
                "E0312" => ("no such field", Type,
                    "The struct doesn't have a field with this name. Check the struct definition for available fields.",
                    "struct Point { x: i32, y: i32 }\nlet p = Point { x: 1, y: 2 }\np.z  // error: no field 'z' on Point"),
                "E0313" => ("no such method", Type,
                    "The type doesn't have a method with this name. Check the extend blocks for available methods, or verify the receiver type.",
                    "let v = Vec.new()\nv.length()  // error: did you mean v.len()?"),
                "E0314" => ("infinite type", Type,
                    "A type would need to contain itself without indirection, creating an infinite-size type. Use `Heap<T>` for indirection.",
                    "struct Node {\n    next: Node  // error: infinite size\n    // fix: next: Heap<Node>?\n}"),
                "E0315" => ("cannot infer type", Type,
                    "The compiler can't determine a type from context alone. Add an explicit type annotation.",
                    "let x = Vec.new()  // error: Vec of what?\n// fix: let x: Vec<i32> = Vec.new()"),
                "E0316" => ("invalid try context", Type,
                    "`try` propagates errors to the caller, so the enclosing function must return `T or E` (a Result type).",
                    "func f() {\n    let x = try might_fail()  // error: f() doesn't return Result\n}"),
                "E0317" => ("try outside function", Type,
                    "`try` can only appear inside a function body. It needs a function return type to propagate errors to.",
                    "let x = try some_call()  // error: not in a function"),
                "E0318" => ("missing return statement", Type,
                    "A function with a non-void return type doesn't return a value on all paths. Rask requires explicit `return` in functions.",
                    "func double(x: i32) -> i32 {\n    x * 2  // error: missing 'return'\n    // fix: return x * 2\n}"),
                "E0319" => ("generic argument error", Type,
                    "A generic type was instantiated with the wrong number or kind of arguments.",
                    "// Vec takes 1 type param\nlet x: Vec<i32, string> = Vec.new()  // error"),
                "E0320" => ("aliasing violation", Type,
                    "A value was mutated while it's being borrowed. Finish using the borrow before mutating, or clone the value.",
                    "let v = Vec.new()\nlet first = v[0]  // borrows v\nv.push(4)  // error: v is borrowed"),
                "E0321" => ("mutate read-only parameter", Type,
                    "Parameters are read-only by default in Rask. To modify a parameter, add the `mutate` keyword.",
                    "func reset(v: Vec<i32>) {\n    v.clear()  // error: v is read-only\n}\n// fix: func reset(mutate v: Vec<i32>)"),
                "E0322" => ("volatile view stored", Type,
                    "A view (reference) into a growable collection was stored across a statement boundary. Views into Vec, Pool, and Map are instant — they're released at the semicolon.",
                    "let v = Vec.new()\nlet elem = v[0]  // view into v\n// elem is invalid after this line if v changes"),
                "E0323" => ("mutate while viewed", Type,
                    "A collection was mutated while a view into it exists. This could invalidate the view. Finish using the view first.",
                    "let v = Vec.new()\nlet elem = v[0]\nv.push(4)  // error: v viewed by elem"),
                "E0324" => ("heap allocation in @no_alloc function", Type,
                    "@no_alloc functions run in real-time contexts where heap allocation causes unpredictable latency. Use stack-allocated alternatives or pre-allocated buffers.",
                    "@no_alloc\nfunc process(data: [f32; 64]) {\n    let v = Vec.new()  // error: allocates\n}"),
                "E0325" => ("write in frozen pool context", Type,
                    "A `using frozen Pool<T>` context is read-only (mem.pools/PF5): no writes through handles, and no insert/remove/clear. Drop `frozen` if the function needs to mutate the pool.",
                    "func heal(h: Handle<Player>) using frozen Pool<Player> {\n    h.health += 10  // error: frozen context\n}\n// fix: using Pool<Player>  (drop `frozen`)"),
                "E0327" => ("required `Link<T>` edge unsupported", Type,
                    "A required edge (`Link<T>` with no `?`) needs a batch to construct — a cycle needs one side written before its target exists — and a declared delete policy (cascade or restrict) for when its target dies, because there is no `none` to set it to. Neither is implemented yet, so write `Link<T>?`. Inside a container a bare link is fine, because delete drops the entry rather than nulling it.",
                    "struct Entity {\n    target: Link<Entity>     // error: no `none` to fall back to\n    target2: Link<Entity>?   // fix\n    children: Vec<Link<Entity>>  // fine: delete drops the entry\n}"),
                "E0328" => ("use after delete on a `Link<T>`", Type,
                    "A `Link<T>` is a pointer to a node, and `rack.delete` frees that node — so every name for it dies at once. This is a use after free, proven at compile time. A link held in a `Link<T>?` *field* survives a delete, because the rack nulls it and the `?` makes you check; a local can't be reached by the rack, so the compiler tracks it instead. Note the invalidation point is the `delete` you wrote, not an inferred last use — the analysis stays inside one function body.",
                    "let n = rack.insert(Node { name: \"a\" })\nrack.delete(n)\nprintln(\"{n.name}\")   // error: `n` names a deleted node\n\n// fix: read before deleting\nlet label = n.name\nrack.delete(n)\nprintln(\"{label}\")"),
                "E0378" => ("node written through a rack you may only read", Type,
                    "A `Link<T>` is a path to a node, not permission to change it. The node lives in a rack, so the rack is what says whether it may be written — the same rule `Handle` has always had, where `scene.nodes[h].f = x` needs `mutate scene`. Asking the rack rather than the link is also what makes a read-only graph free: a function taking `s: Rack<T>` can read every node and write none, and because the question is about the rack, following an edge doesn\'t change the answer — there is nothing to propagate and no way to launder a readable link into a writable one.",
                    "func combat(world: Rack<Entity>) {\n    for e in world.nodes() {\n        if e.target? as t { t.health -= e.damage }   // error: `world` is only readable\n    }\n}\n\n// fix: say the nodes get written\nfunc combat(mutate world: Rack<Entity>) {\n    for e in world.nodes() {\n        if e.target? as t { t.health -= e.damage }\n    }\n}"),
                "E0331" => ("mutation method on `string`", Type,
                    "`string` is immutable (std.strings/S7). It's a 16-byte value and every copy shares one buffer, so an in-place write would change copies you never touched. `StringBuilder` is the mutable one: it owns its buffer alone, and `build()` transfers it to a string without copying.",
                    "mut out = \"\"\nout.push_str(\"hello\")   // error: string has no push_str\n\n// fix:\nmut b = StringBuilder.new()\nb.push(\"hello\")\nb.push_char('!')\nlet out = b.build()"),
                "E0342" => ("unknown context", Type,
                    "A `using` block references a context that doesn't exist. Valid contexts are `Multitasking` and `ThreadPool`.",
                    "using Foo {\n    // error: unknown context `Foo`\n}"),
                "E0345" => ("type name called as a function", Type,
                    "`Name(value)` is the constructor for a nominal type declared with `type Name = Underlying` (T7). Structs have named fields and no tuple form (S1), so they're built with a literal; enums are named by variant.",
                    "struct TaskId { public value: u64 }\n\nlet a = TaskId(1)             // error\nlet b = TaskId { value: 1 }   // fix"),
                "E0346" => ("task-local Shared sent to another task", Type,
                    "`Shared<T, Local>` takes no lock, so it may only be reached from the task that made it. Sending one to another task would be a data race, so it's rejected. `Local` is the opt-out; this rule is what makes it safe to reach for (conc.sync/SH7).",
                    "let counter = Shared.local(0)\nlet h = spawn(|| {\n    with counter.write() as c { c += 1 }   // error\n})\n\n// fix: a strategy that locks\nlet counter = Shared.new(0)"),
                "E0380" => ("retired box type", Type,
                    "`Cell` and `Mutex` were separate box types. They were one concept with `Shared` — one value, several accessors, a scoped view — differing only in what synchronization they took, so they became strategies on `Shared<T, S>` (analysis.storage-consolidation).",
                    "let c = Cell.new(0)          // error\nlet m = Mutex.new(0)         // error\n\n// fix:\nlet c = Shared.local(0)      // no lock, one task\nlet m = Shared.mutex(0)      // a plain lock"),
                "E0381" => ("Shared strategy mismatch", Type,
                    "The strategy in `Shared<T, S>` decides which lock the accessors take, so the constructor and the annotation have to agree. A bare `Shared<T>` means `Shared<T, Readers>` (conc.sync/SH2) — it is a defaulted parameter, not an absent one. Code that works under any strategy says so: `func serve<S>(c: Shared<Config, S>)` (SH4).",
                    "func bump(c: Shared<i32>) -> i32 {      // Shared<i32, Readers>\n    with c.write() as v { return v + 1 }\n}\n\nlet c = Shared.local(0)                 // Shared<i32, Local>\nbump(c)                                 // error\n\n// fix: agree on one, or be generic over it\nfunc bump<S>(c: Shared<i32, S>) -> i32 { ... }"),
                "E0351" => ("runtime context on signature", Type,
                    "`using Multitasking` and `using ThreadPool` install a process-global runtime slot. They cannot appear on function signatures — only on block expressions.",
                    "// Error: signature-level using is not allowed\nfunc run_tasks() using Multitasking { }\n\n// Fix: wrap the call site instead\nfunc main() {\n    using Multitasking {\n        run_tasks()\n    }\n}"),
                "E0352" => ("spawn outside multitasking block", Type,
                    "`spawn` requires an active `using Multitasking { ... }` block to be in scope. Without a runtime, there's nowhere to submit the task.",
                    "func main() {\n    spawn { do_work() }  // error: no `using Multitasking` block\n\n    // Fix:\n    using Multitasking {\n        spawn { do_work() }  // ok\n    }\n}"),
                "E0353" => ("transitive spawn outside multitasking block", Type,
                    "A function that transitively calls `spawn` is being called without an active `using Multitasking { ... }` runtime scope. The call will panic at runtime.",
                    "func do_work() {\n    spawn(|| { task() })  // reaches spawn\n}\n\nfunc main() {\n    do_work()  // error: no runtime scope\n\n    // Fix:\n    using Multitasking {\n        do_work()  // ok\n    }\n}"),
                "E0354" => ("duplicate variant in sum type", Type,
                    "A sum type cannot contain the same payload variant twice — `(T or E) or E` is ambiguous, because the compiler picks the branch from the value's type and an `E` value fits both. `none` is exempt: `T??` is a legal two-layer optional whose layers stay distinct. Use a named enum if you need two flavours of the same error.",
                    "// Error: duplicate `ParseError` branch\nfunc f() -> (i32 or ParseError) or ParseError { }\n\n// Fix: use a named enum\nenum LookupResult { Found(User), Missing, Forbidden }\nlet x: LookupResult = LookupResult.Missing"),
                "E0358" => ("generic instantiation collapses `T or E`", Type,
                    "A generic returning `T or E` was called with a type argument equal to `E`. Both branches would then carry the same type and the caller could not tell a success from an error. The signature's `T or E` is itself the requirement that they stay distinct — it is checked here, at the call, where the type argument is known. Newtype one side to keep them apart.",
                    "enum CacheError { Miss }\n\nfunc cached<T>(v: T) -> T or CacheError { return v }\n\nfunc main() {\n    let ok = cached(42)                 // T = i32: fine\n    let bad = cached(CacheError.Miss)   // error: T = CacheError\n\n    // Fix: newtype the success side\n    type Cached = CacheError with (…)\n}"),
                "E0356" => ("unknown type in signature", Type,
                    "A PascalCase name in a function signature doesn't resolve to any declared type. Only single uppercase letters (T, U, K, V) are auto-generic type parameters — longer names must be declared types. This catches typos early instead of silently treating them as generics.",
                    "struct Config { port: i32 }\nfunc load(c: Confg) { }  // error: did you mean `Config`?\n\n// Auto-generic still works with single letters:\nfunc swap(a: T, b: T) -> (T, T) { return (b, a) }"),
                "E0357" => ("single-letter type name", Type,
                    "Single uppercase letters are reserved for type parameters. A struct, enum, trait, or union named `T` would be shadowed by the type-parameter convention in every signature.",
                    "struct T { }  // error: reserved for type parameters\n// fix: struct Token { }"),
                "E0355" => ("error type mismatch in try", Type,
                    "`try` propagates the inner error to the enclosing function, so the two error types have to line up. They line up three ways: the same type, a member of the function's error union, or a single-payload variant of the function's error enum. Anything else needs the wrap named at the call — `expr catch e => return …`.",
                    "enum ParseError { Syntax(string) }\nenum ApiError { Parse(ParseError), BadRequest(string) }\n\nfunc inner() -> i32 or ParseError { return 42 }\n\nfunc outer() -> i32 or ApiError {\n    let x = try inner()  // ok: ApiError.Parse takes a single ParseError\n    return x\n}"),
                "E0359" => ("ambiguous error wrap in try", Type,
                    "Two or more variants of the function's error enum take the propagated error as their only payload, so `try` has no way to choose. Name the variant at the call site.",
                    "enum StoreError { NotFound(string) }\nenum ApiError { Store(StoreError), Fatal(StoreError) }\n\nfunc outer() -> i32 or ApiError {\n    let x = try lookup()  // error: Store or Fatal?\n\n    // Fix: say which\n    let y = lookup() catch e => return ApiError.Store(e)\n    return y\n}"),
                "E0361" => ("type could not be inferred", Type,
                    "Inference finished with this binding's type still open. Usually nothing in scope constrains it — a `Vec.new()` that never gets pushed to, a const whose initializer the compiler can't evaluate. Writing the type out settles it. If it looks like it should have been inferable, that's a compiler bug: the alternative to this error is guessing a size, which silently corrupts floats, strings and structs.",
                    "let v = Vec.new()          // error: couldn't work out the type of `v`\nlet v: Vec<i64> = Vec.new()  // fix"),
                "E0364" => ("`??` on a result", Type,
                    "`??` fills in a missing value, and only an optional (`T?`) can be missing. A `T or E` carries an error instead, and dropping it silently is what `??` would do here — `catch` says out loud that an error is being discarded.",
                    "let n = parse(text) ?? 0        // error: parse returns `i64 or ParseError`\nlet n = parse(text) catch _ => 0  // fix: the discard is visible"),
                "E0360" => ("mutate through shared read lock", Type,
                    "`.read()` takes a shared lock — other readers may hold it at the same time, so its binding is read-only and never writes back. Use `.write()` for exclusive access when you need to mutate.",
                    "let config = Shared.new(Config {})\nwith config.read() as c {\n    c.timeout = 10   // error: read lock\n}\n// fix:\nwith config.write() as c {\n    c.timeout = 10   // exclusive — written back at block exit\n}"),

                // Trait errors (E07xx)
                "E0700" => ("trait bound not satisfied", Trait,
                    "A generic function requires a trait bound that the provided type doesn't implement.",
                    "func print_it<T: Display>(x: T) { }\nprint_it(MyStruct {})  // error: MyStruct doesn't implement Display"),
                "E0701" => ("missing trait method", Trait,
                    "An `extend` block claims to implement a trait but doesn't define all required methods.",
                    "trait Printable { func show(self) }\nextend Point as Printable { }  // error: missing show()"),
                "E0702" => ("method signature mismatch", Trait,
                    "A trait method implementation has a different signature than the trait declaration.",
                    "trait Add { func add(self, other: Self) -> Self }\nextend Point as Add {\n    func add(self) -> Self { }  // error: wrong params\n}"),
                "E0703" => ("unknown trait", Trait,
                    "A trait name was used that doesn't exist. Check spelling and imports.",
                    "extend Point as Printabel { }  // error: did you mean Printable?"),
                "E0704" => ("conflicting trait methods", Trait,
                    "Two trait implementations provide the same method name for a type. This creates ambiguity.",
                    "// Both TraitA and TraitB define show()"),

                // Ownership errors (E08xx)
                "E0800" => ("use after move", Ownership,
                    "A value was used after being moved. Once ownership transfers, the original binding is invalid. Clone if you need both.",
                    "let v = Vec.new()\ntake_ownership(own v)\nv.len()  // error: v was moved"),
                "E0801" => ("borrow conflict", Ownership,
                    "Multiple borrows conflict — typically a mutable borrow while an immutable borrow exists.",
                    "let v = Vec.new()\nlet first = v[0]  // immutable borrow\nv.push(4)  // error: mutable borrow conflicts"),
                "E0802" => ("mutate while borrowed", Ownership,
                    "A value was mutated while it's borrowed. The borrow must end before mutation is allowed.",
                    "let s = \"hello\"\nlet r = s\ns = \"world\"  // error: s is borrowed by r"),
                "E0803" => ("instant borrow escapes", Ownership,
                    "A reference from a collection access was stored past its valid scope. Collection references are instant — valid for one expression only.",
                    "let v = Vec.new()\nlet elem = v[0]\n// elem may be invalid if v reallocates"),
                "E0804" => ("borrow escapes scope", Ownership,
                    "A reference outlives the value it borrows from. The borrowed value must live at least as long as the reference.",
                    "func bad() -> string {\n    let local = \"temp\"\n    return local  // error if local is stack-allocated\n}"),
                "E0805" => ("resource not consumed", Ownership,
                    "A resource-typed value (marked with @resource) wasn't properly consumed. Resource types must be explicitly closed, released, or passed to a consuming function.",
                    "func open_file() {\n    let f = fs.open(\"data.txt\")\n    // error: f not consumed (must call f.close())\n}"),
                "E0806" => ("move from borrowed parameter", Ownership,
                    "A borrowed parameter was used in a context that requires ownership. Parameters are borrowed by default — the caller retains ownership. Use `take` to transfer ownership into the function.",
                    "func push(self, value: T) {\n    self.data[i] = value  // error: value is borrowed\n}\n// fix: func push(self, take value: T)"),
                "E0811" => ("use after discard", Ownership,
                    "`discard` explicitly drops a value and invalidates its binding. Using the binding after `discard` is a compile error (D1).",
                    "let data = load_data()\ndiscard data\nprintln(data)  // error: use of discarded value"),
                "E0812" => ("discard resource type", Ownership,
                    "Resource types (@resource) must be consumed properly via their consuming method (.close(), .release(), etc). `discard` on a resource type is a compile error (D3).",
                    "@resource\nstruct File { fd: i32 }\nlet f = File { fd: 1 }\ndiscard f  // error: use f.close() instead"),
                "E0813" => ("use after maybe-move", Ownership,
                    "A value moved on some paths but not all (e.g. one `if` branch) was used after the paths merged. The spec treats maybe-moved as moved (O3) — move on every path, or keep the use inside the branch that still owns the value.",
                    "let v = Vec.new()\nif c { take(own v) }\nv.len()  // error: v may have been moved"),
                "E0817" => ("invalid `as` cast", Type,
                    "`as` permits only lossless widening (CV1). Narrowing, sign reinterpretation, float↔int, int→char, and int↔bool are compile errors — name a policy with one of the six conversion methods (`to`, `wrap`, `clamp`, `round`, `floor`, `ceil`) or with `char.from_u32`.",
                    "let x: i8 = big as i8  // error: use `big.to<i8>()!`, `big.wrap<i8>()` or `big.clamp<i8>()`"),
                "E0818" => ("invalid conversion form", Type,
                    "A conversion method was used where its policy means nothing (CV11–CV16). Each is defined only on the source and target kinds it can say something about: `wrap` and `clamp` are integer-to-integer, `floor` and `ceil` are float-to-integer, and `round` is anything but integer-to-integer — there is nothing to round there. Anywhere else is an error rather than a no-op, so a method that reads as if it did something always did.",
                    "let x = n.floor<i32>()   // error if n is already an integer\n// fix: `n.to<i32>()!`, `n.wrap<i32>()` or `n.clamp<i32>()`"),
                "E0819" => ("index type mismatch", Type,
                    "An index expression `c[i]` used the wrong index type. Vec, arrays, slices, and strings are position-indexed by an integer; `Map<K,V>` is indexed by `K`; `Pool<T>` is indexed by `Handle<T>`. Range indexing (slicing) only works on Vec, arrays, slices, and strings.",
                    "let s = \"hi\"\nv[s]  // error: index a Vec with an integer, not a string"),
                "E0820" => ("linear value in container", Ownership,
                    "A Vec or Map element (or Map key) is a linear value — an @resource type, a transitively-linear struct/enum, or an optional/tuple/array built from one. Vec/Map drop can't consume linear elements, so they'd be silently dropped (RC1/RC3). Use `Pool<T>` (explicit removal, RC2) or `T?` (match and consume, RC4).",
                    "@resource\nstruct File { fd: i32 }\nlet files: Vec<File> = Vec.new()  // error: use Pool<File>"),
                "E0821" => ("ensure receiver maybe-consumed", Ownership,
                    "A resource with a pending `ensure` was consumed on some paths but not all, and the paths merge before scope exit (C4). Which cleanup runs must be statically definite — never decided by hidden runtime state (C3). Exit inside the consuming branch, or consume on every path.",
                    "let tx = try db.begin()\nensure tx.rollback()\nif fast { tx.commit() }  // error: paths merge with tx maybe-consumed\nlog(\"done\")"),
                "E0822" => ("missing struct field", Type,
                    "A struct literal left out a field that has no default value. Construction never zero-initializes — a defaultless field must be given a value, or declared with a default (`field: T = value`). A spread (`..base`) supplies every unlisted field.",
                    "struct Config { host: string, port: i32 = 8080 }\nlet c = Config {}  // error: missing field `host`"),
                "E0823" => ("method name shared by two types", Type,
                    "Two different types have the same name — usually a program type and a stdlib one — and both define this method. Compiled functions are identified by `Type_method`, so the two methods want the same name and only one can have it. The type the name currently refers to gets it; a call needing the other has nowhere to go. Rename one of the types.",
                    "// stdlib already has `enum JsonError` with `message()`\nstruct JsonError { detail: string }\nextend JsonError {\n    func message(self) -> string { return self.detail }\n}\n// fix: name it something else, e.g. `ConfigJsonError`"),
                "E0824" => ("public duck trait", Type,
                    "A `duck trait` was declared `public`. Duck traits match by shape instead of by declaration, which makes them a versioning trap across a package boundary: an external type could start or stop satisfying the trait because its author added or removed a method, with nothing in either diff to notice. So duck traits stay package-internal (type.generics/DT1) — they're for code you're still sketching. Drop `duck` to harden the trait (the compiler generates the conformance declarations for types that already match), or drop `public`.",
                    "public duck trait Frobber {\n    func frobnicate(self)\n}\n// fix: `public trait Frobber` (nominal), or `duck trait Frobber` (package-internal)"),
                "E0825" => ("integer literal out of range", Type,
                    "An integer literal doesn't fit the type it ended up with. Unsuffixed literals are `i32` by default (type.primitives/L1) and widen to `i64` when the value needs it; a literal that reaches a narrower type through an annotation, a suffix, or a parameter has to fit that type. Nothing wraps silently — pick a wider type, or convert at the use site.",
                    "let b: u8 = 300  // error: 300 doesn't fit u8 (0..=255)\n// fix: `let b: u16 = 300`, or `let b = (300 as i64).wrap<u8>()`"),
                "E0826" => ("type does not implement Displayable", Type,
                    "`{}` in a format template calls `to_string()`, which comes from `Displayable` (std.fmt/D4). Primitives have it; structs and enums opt in with `extend Type with Displayable`, and error types get it for free from `message()` (D5). Optionals and results are never Displayable — an optional may have nothing to show, so the missing case has to be spelled out at the call.",
                    "let found: User? = lookup(id)\nprintln(\"{found}\")   // error: `User?` has no to_string()\n// fix: `println(\"{found ?? \\\"nobody\\\"}\")`, or narrow first with `if found? as u { … }`"),
                "E0827" => ("type can't be iterated", Type,
                    "A `for` loop walks a Vec, Map, Pool, array, slice, range or iterator chain. The thing in the iterator position resolved to a single value instead — most often a count where the range was meant, a string where `.chars()` was meant, or a struct where one of its collection fields was meant. A container reached through a field resolves later than the loop, so this is reported once its type settles rather than at the loop itself.",
                    "for x in self.count { … }   // error: `i64` can't be iterated\n// fix: `for x in 0..self.count { … }`"),
                "E0829" => ("with guard escapes its block", Type,
                    "A `with` block's guard — the name after `as` — is access to a box's payload for the block's duration, not a value of its own: boxes hand out no guards, so the inner value can't outlive its scope. Returning the bare guard identifier as the block's own produced value would hand back a live view into memory the lock no longer protects once the block ends. This only fires for struct/enum/union payloads; scalars and `string` copy out fine as-is, since a plain identifier read of those is already an independent value.",
                    "let c = with counter as g { g }   // error: `g` (a `Counter`) can't leave the block\n// fix: `with counter as g { g.hits }`, or a method that returns an owned `Counter`"),
                "E0838" => ("`as` to a target it can't convert to", Type,
                    "`as` has exactly two meanings: converting between numbers (CV1) and boxing a value as a trait object (`as any Trait`, TR5). To a collection, a struct, or an enum there is nothing left for it to mean but reinterpreting the bits, which is what `transmute` needs `unsafe` for. It used to be accepted silently with no check at all, so `[1, 2, 3] as Vec<i64>` lowered to a stack array whose address was handed to `Vec_len` — and indexing the result segfaulted from ordinary safe code. To give a value a type, annotate the binding; to reinterpret on purpose, say `unsafe`.",
                    "let v = [1, 2, 3] as Vec<i64>  // error
// fix: let v: Vec<i64> = [1, 2, 3]"),
                "E0837" => ("a `Heap` value was never dropped", Ownership,
                    "`Heap(…)` allocates, and the value has exactly one owner who has to consume it exactly once (mem.linear/L1) — otherwise the allocation is never freed. Consuming it means `drop(name)`, handing it to a `take` parameter, storing it in a field or enum payload, or returning it. `ensure` works too when the consumption happens on an error path. This is the same rule `@resource` follows; only the spelling of the fix differs.",
                    "let p = own Node { v: 7 }\nprintln(\"{p.v}\")      // error: `p` is never dropped\n// fix: add `drop(p)`"),
                "E0836" => ("a `mutate` parameter was left empty", Ownership,
                    "`mutate` is exclusive access, not ownership (mem.parameters/PM2): the caller keeps the value and goes on reading it after the call. That makes taking the value out and writing a replacement back legitimate — `out.push(b.build()); b = StringBuilder.new()` is exactly what the mode is for. Consuming it and putting nothing back is not: the caller reads a hole. A replacement has to be assigned on every path that reaches the return. If the function really does take the value for good, declare the parameter `take` instead — then the call site shows it going.",
                    "func drain(mutate b: StringBuilder) -> string {\n    return b.build()      // error: consumed, nothing put back\n}\n// fix: `func drain(take b: StringBuilder) -> string`"),
                "E0835" => ("cannot give away a borrowed parameter", Ownership,
                    "A parameter declared without `take` is the caller's value on loan (mem.parameters/PM1): they keep it and go on using it after the call. Handing it to a `take` parameter, an `own` argument, or a `take self` method would consume something the callee doesn't own — the caller is never told, and for a `@resource` that is a second close of a live handle. `mutate` is the same answer for a different reason: exclusive access lets you write through the parameter, not give it away. Put `take` on the declaration if the function really does consume its argument; then the call site shows the value going.",
                    "func handle(c: Conn) { c.close() }   // error: `close` takes ownership\n// fix: `func handle(take c: Conn) { c.close() }`"),
                "E0834" => ("type can't be a Map key", Type,
                    "A Map key has to be Hashable: equal keys must hash equal, or a key can be inserted and then never found again (type.generics/HA1). Auto-derive covers the primitives, a struct or enum whose every field or payload is itself Hashable, and a tuple or array of Hashable elements (type.tuples/TU11). Three things are left out — `f32`/`f64`, because `NaN != NaN` breaks the contract outright (HA4); an aggregate that reaches a float through one of its fields; and a nominal newtype, which inherits only the traits its `with (…)` clause names (type.aliases/T11).",
                    "type Id = u64\nlet ids: Map<Id, User> = Map.new()   // error: `Id` is not Hashable\n// fix: `type Id = u64 with (Equal, Hashable)`"),
                "E0833" => ("no trait by that name", Type,
                    "A bound, a conformance header, or an `as any Trait` cast named something that isn\'t a trait. Usually a typo or a missing import. This used to be reported as \"`_` does not implement X\" — an unknown trait has no type to blame, so the placeholder stood in for one and the message pointed at the type system instead of at the name (type.generics/G1).",
                    "func narrow<T: Intger>(x: i64) -> T { … }   // error: no trait named `Intger`\n// fix: `func narrow<T: Integer>(x: i64) -> T { … }`"),
                "E0832" => ("`!` on a value that is always there", Type,
                    "`x!` extracts the payload of a `T?` and panics when the value is absent (type.optionals/OPT13). On a left side that can never be absent there is no wrapper to extract from and nothing that could panic, so the operator has no meaning. This usually turns up after a refactor that made something non-optional and left the `!` behind. Drop it. Note `!` is also boolean negation, and on a `bool?` neither reading applies — that case is E0830.",
                    "let n: i64 = 5\nlet v = n!   // error: `i64` has no payload to force out\n// fix: `let v = n`"),
                "E0377" => ("excluded field has no default to decode from", Type,
                    "A decode has to build the whole struct, and a `private` or `@no_serialize` field never appears in the input — so its value comes from its declared default (type.structs/FD1, FD6) or from nowhere. With neither, the type isn\'t auto-`Decode` (std.encoding/E13a). Encoding is unaffected: it never needs a value for a field it omits, which is why the same type can be `Encode` and not `Decode`.",
                    "struct Config {\n    public host: string\n    @no_serialize\n    public token: string    // error: nothing to fill `token` on decode\n}\n// fix: `public token: string = \"\"`, or `@default(\"\")` for a decode-only default"),
                "E0376" => ("serialization annotation the compiler can\'t act on", Type,
                    "`@rename` takes a string literal and `@default` a comptime expression (std.encoding/E21), and both are checked at the declaration rather than at the encode site — an annotation the compiler silently ignores is worse than one it rejects, because the wire format then differs from what the source says. `@skip` is here too: it was renamed to `@no_serialize` because \"skip\" didn\'t say skip from what (E19), and left alone it reads as \"excluded\" while still serializing the field.",
                    "@skip\npublic token: string   // error: `@skip` is now `@no_serialize`\n\n@rename(user_name)\npublic name: string    // error: the serialized key has to be a string literal\n// fix: `@rename(\"user_name\")`"),
                "E0374" => ("`@small` type outgrew the copy threshold", Ownership,
                    "`@small` asserts one thing: the type stays within the 16-byte copy threshold (mem.value/SM1). It changes no semantics — what it buys is the *location* of the break. Without it, adding a field that pushes a struct past 16 bytes flips every assignment from copy to move, and those errors land wherever the type is used, with only the move note pointing back at the field nobody was looking at. With it, the error is at the declaration, before any call site sees it (mem.value/SM2). It composes with `@unique`: one is about layout, the other about copy semantics (SM4).",
                    "@small\nstruct Point { x: i64, y: i64, z: i64 }   // error: 24 bytes\n// fix: drop a field, shrink the fields (`x: i32`), or drop `@small`"),
                "E0375" => ("`@small` generic doesn\'t fit at this instantiation", Ownership,
                    "The fence is written at the definition but it is a promise about every instantiation, so it is checked per instantiation like any other generic bound (mem.value/SM3, type.generics/G2). The same source text can be 16 bytes at one type argument and 32 at another; only the second breaks the promise, and callers reading `@small` off the declaration have no way to tell which one they got. Rask has no size bound to narrow `T` with, so the two fixes are: don\'t instantiate it that wide, or drop the fence.",
                    "@small\nstruct Pair<T> { a: T, b: T }\nlet p = Pair<string> { a: \"x\", b: \"y\" }   // error: 32 bytes at `Pair<string>`\n// fix: `Pair<i64>` is 16 and fine — or drop `@small` from `Pair`"),
                "E0370" => ("integer doesn\'t fit its target", Type,
                    "An integer went into a position too small for it, or into one whose signedness can\'t hold it. Widening is implicit precisely because it can\'t fail (type.primitives/CV1a); this can, so the site says what to do with a value that doesn\'t fit rather than the compiler guessing. `u64` → `i64` and `i64` → `u64` are both here: the first has values above `i64.MAX`, the second has negatives.",
                    "let small: u8 = big   // error: `i64` doesn\'t fit in `u8`\n// fix: `let small = big.to<u8>()!` (assert it fits), `big.wrap<u8>()` (low bits), or `big.clamp<u8>()` (clamp)"),
                "E0371" => ("arithmetic across signedness", Type,
                    "`+ - * / %` and `& | ^ << >>` need both operands in the same type, and a signed and an unsigned integer have no common one — `u64` can\'t hold a negative `i32`, and `i32` can\'t hold a large `u64`. Widening one side quietly is the conversion C makes, and it\'s why `-1 < 1u` is true there; Rask asks instead. Comparison is the deliberate exception (type.operators/ORD4): `5u64 > -1i32` answers by value, so there is nothing to guess. Convert one side and say what happens when it doesn\'t fit.",
                    "let u: u64 = 5\nlet i: i32 = -10\nlet sum = u + i   // error: `+` between `u64` and `i32`\n// fix: `let sum = u + i.wrap<u64>()`, or work in i64: `u.wrap<i64>() + i`\nlet ordered = u > i   // fine — comparison crosses signedness (ORD4)"),
                "E0372" => ("write through a binding", Type,
                    "A name a test or a pattern introduced isn\'t a slot. `if x? as v`, `r is E as e`, a match-arm payload and `catch e =>` all name the value the test proved was there, read out of the scrutinee (type.optionals/OPT19 binds a let) — a write to the name would land on that copy and never reach the original. A `for` element is the same, with a different remedy: a plain `for` walks read-only, and `for mutate x in xs` is the mode whose writes reach the collection (std.iteration/I1, I4). This used to be E0322, whose fix was \"add `mut`\" — not writable at any of these sites, since `if x? as mut v` doesn\'t parse.",
                    "if opt? as t { t.n += 1 }   // error: `t` is a binding\n// fix: copy out, then write the whole value back\nif opt? as t {\n    mut next = Counter { n: t.n + 1 }\n    opt = next\n}\n\nfor c in xs { c.n += 1 }   // error: `c` is a read-only element\n// fix: `for mutate c in xs { c.n += 1 }`"),
                "E0373" => ("missing call-site `mutate` marker", Type,
                    "An argument going into a `mutate` parameter is written `mutate arg` (mem.parameters/PM4). This is asymmetry, not ceremony: a misread *move* is already caught — using a value after it moved is a compile error — but nothing catches a misread mutation, because `apply(player, 10)` reading as \"looks at player\" and \"rewrites player\" are both legal code. So the reading the compiler can\'t backstop is the one the source states. PM5: the marker follows the signature, never the argument\'s size, so a Copy argument writes it too. A method receiver is exempt — `player.take_damage(10)` operates on the receiver by construction. The marker on a parameter that *isn\'t* `mutate` is E0328: a marker with no mutation behind it is a lie.",
                    "func apply_damage(mutate p: Player, amount: i64) { … }\napply_damage(player, 10)   // error: mark it at the call site\n// fix: `apply_damage(mutate player, 10)`\n\nplayer.take_damage(10)     // fine — receivers are exempt"),
                "E0365" => ("`take` on a non-optional place", Type,
                    "`take slot` moves the payload out and leaves `none` behind (type.optionals/OPT32), so the place has to have an absent branch to leave. A place that is always there has none: reading it is just `slot`. On a `T or E` the answer is `match` — an error is not a slot you empty. The place\'s type often comes from a struct field, so this is reported once that field resolves rather than at the `take`.",
                    "struct Connection { pending: Request }\nlet req = take conn.pending   // error: `Request` is not a `T?` place\n// fix: declare it `pending: Request?`"),
                "E0831" => ("`??` on a value that is always there", Type,
                    "`??` supplies the branch a `T?` has and a plain value doesn't (type.optionals/OPT3, OPT11). On a left side that can never be absent there is nothing for the right side to be, so the operator has no meaning and no lowering. The usual way to get here is indexing: `m[k]` and `v[i]` panic when the element isn't there rather than handing back a `T?`, so a `??` after one reads like a miss-handler and isn't. Ask for the optional directly with `.get(k)`. For a `T or E` the answer is different — that's a failure, not an absence, and it's `catch` (E0364).",
                    "let v: i64 = m[key] ?? -1   // error: `m[key]` is an `i64`, always there\n// fix: `let v: i64 = m.get(key) ?? -1`"),
                "E0830" => ("`!` on an optional", Type,
                    "`!` negates a `bool`; a `T?` doesn't coerce to `T` (type.optionals/OPT5), so `!` doesn't reach through the wrapper. This matters most on `bool?`, where the payload's type makes `!x` look applicable — but a reader can't tell whether it negates the payload or tests for absence, and `x!` already means force-unwrap on the same operand. Test presence with `x is none`, or narrow first with `if x? as v { !v }`.",
                    "let x: bool? = flag()\nlet y = !x   // error: negation doesn't reach through the optional\n// fix: `if x? as v { !v }`, or `x is none` to test absence"),
                "E0831" => ("`using` context on the entry point", Type,
                    "A `using` clause is a hidden parameter (mem.context/CC11): callers pass the context in, and the compiler finds it by searching the caller's scope. The entry point has no caller — the process starts there — so that parameter is never written and holds whatever the stack happened to contain. Own the context instead: build it as a local in the entry point and call the functions that declare `using`; they resolve it out of your scope automatically.",
                    "func main() using players: Pool<Player> {   // error: nothing can supply this\n    spawn_wave(10)\n}\n\n// fix: own the pool in main, leave the clause on the callee\nfunc main() {\n    mut players: Pool<Player> = Pool.new()\n    spawn_wave(10)   // resolves `players` from main's scope\n}\n\nfunc spawn_wave(n: i64) using players: Pool<Player> { }"),
                "E0841" => ("`@tag` on a variant with an unnamed payload", Type,
                    "Internal tagging writes the tag as a field *inside* the payload\'s object, beside the payload\'s own fields (std.encoding/E24). That needs field names to write: a variant whose payload is unnamed has exactly one value and no key to put it under, so the tag and the payload can\'t share the object without the compiler inventing a name. Either name the field, or drop `@tag` and let the variant encode externally (E22/E23), where the variant name is the key and an unnamed payload goes in directly.",
                    "@tag(\"type\")\nenum Shape {\n    Circle(f64)          // error: unnamed payload can\'t carry the tag\n}\n// fix: name it\n@tag(\"type\")\nenum Shape {\n    Circle { radius: f64 }   // → {\"type\": \"Circle\", \"radius\": 1.0}\n}"),
                "E0842" => ("`@tag` name collides with a payload field", Type,
                    "The tag is written as a field in the same object as the payload\'s own fields (std.encoding/E24), so a payload field with the tag\'s name would produce the key twice. Duplicate keys aren\'t valid JSON, and a decoder reading it back keeps only one — losing either the discriminant or the field. Nothing here is guessable, so it\'s rejected at the declaration: rename the tag or rename the field.",
                    "@tag(\"kind\")\nenum Event {\n    Click { kind: string }   // error: `kind` is both the tag and a field\n}\n// fix: rename one of them\n@tag(\"kind\")\nenum Event {\n    Click { button: string }\n}"),
                "E0843" => ("growing a fixed-size array", Type,
                    "A fixed array's length is part of its type: `[i32; 3]` is a different type from `[i32; 4]`, and the storage is exactly three elements wide with nothing after it to grow into. So `push`, `pop`, `insert` and the rest of the length-changing surface aren't operations it has. Until this was rejected they type-checked through the `Vec` method table and then did real damage: the interpreter quietly grew the value past its own type, and native read the first elements as a Vec header and walked off into whatever they happened to spell. Annotate the slot as `Vec<T>` if it needs to grow — the same literal builds one.",
                    "mut a: [i32; 3] = [1, 2, 3]\na.push(4)                    // error: `[i32; 3]` always holds 3 elements\n\n// fix: say it can grow\nmut a: Vec<i32> = [1, 2, 3]\na.push(4)                    // 4 elements"),
                "W0907" => ("multi-field update under a lock without staged()", Type,
                    "Two or more fields of a locked value written in one `with` block, without staging the update. Rask has no lock poisoning: a panic between the two writes releases the lock and the next task in reads whatever landed, so a multi-field invariant other tasks depend on can be observed half-done (ctrl.panic/LK3). `staged()` works on a copy and commits it as one move, which makes that impossible by construction — the clone is the price, and the method name is where it shows. This is a warning rather than an error because partial state is often harmless; where it is, `@allow(torn_lock_update)` on the enclosing function says so. Mutating method calls don't count: a method body is opaque, and flagging every pair of calls would drown the real signal.",
                    "with accounts.write() as a {\n    a.checking = a.checking - amount   // warning: first field\n    a.savings = a.savings + amount     // second\n}\n\n// fix: one commit, or nothing\nwith accounts.staged() as a {\n    a.checking = a.checking - amount\n    a.savings = a.savings + amount\n}"),
                "E0846" => ("`staged()` outside a `with` block", Type,
                    "Staged access takes the lock, binds a working copy, and commits it back as one move when the block exits — that exit is where the commit happens, so there has to be a block. `read` and `write` also have an expression-scoped form, `box.write().field`, where the lock is held for just that chain; staged has no equivalent, because a single expression has no exit to commit at. Until this was rejected the interpreter reported an internal \"no method `staged`\" and native failed codegen with \"Function not found\".",
                    "let n = C.staged().checking        // error: no block to commit at\n\n// fix: a block, or plain exclusive access for one field\nwith C.staged() as a { a.checking = a.checking - 10 }\nlet n = C.write().checking"),
                "E0845" => ("`staged()` under the `Local` strategy", Type,
                    "Staged access takes the exclusive lock, works on a copy, and commits it as one move — so a panic mid-update leaves the last committed state rather than a half-written one. That matters only when another task could read the torn state. `Shared<T, Local>` is the single-task strategy: it takes no lock at all, nothing else can see the value, and a panic that unwinds past the block kills the only task that could. So the clone protects nothing and costs a copy, which is why it is refused at the call site rather than quietly performed.",
                    "const C: Shared<Acc, Local> = Shared.local(Acc { n: 1 })\nwith C.staged() as a { … }      // error: nothing else can observe a tear\n\n// fix: plain exclusive access\nwith C.write() as a { … }"),
                "E0844" => ("`try` inside `ensure`", Type,
                    "An `ensure` body runs at scope exit, on the way out of the function — by then the return value is already decided, and on a panic there is no return at all. So there is nothing for `try` to propagate an error to. That is why cleanup errors are ignored by default (ctrl.ensure/ER1) and `else |e|` exists to observe them (ER2); the same reasoning bars `try` from the handler, which is the last thing that runs (ER3). Until this was rejected the program type-checked, did nothing visible on the interpreter, and failed native codegen with an internal message about a type it couldn\'t work out.",
                    "ensure { let n = try f.close() }        // error: nowhere to propagate to\n\n// fix: observe the error here instead\nensure f.close() else |e| { log(e.message()) }"),
                "E0840" => ("resource discarded as a statement", Ownership,
                    "A resource-typed value (marked @resource, like `TaskHandle` — conc.async/H1) came back from a call used as a bare statement, with nothing to bind it to. The value is produced and dropped in the same instant, before anything could consume it — the same leak `E0805` catches for a named binding that falls out of scope unconsumed, just with no name to point at.",
                    "using Multitasking {\n    spawn(|| { work() })   // error: TaskHandle dropped without join()/detach()\n}\n// fix: let h = spawn(|| { work() })\n//      h.detach()"),
            },
        }
    }
}

impl ErrorCodeRegistry {
    pub fn get(&self, code: &str) -> Option<&ErrorCodeInfo> {
        self.codes.get(code)
    }

    pub fn all(&self) -> impl Iterator<Item = &ErrorCodeInfo> {
        self.codes.values()
    }
}
