# SPDX-License-Identifier: (MIT OR Apache-2.0)
"""Type x carrier matrix generator.

Most codegen bugs are not "feature X is broken" — they are "payload type P does
not survive carrier C". A tuple of f32 breaks while a tuple of i64 works; an
Option of f64 breaks while an Option of a struct works. One program per cell
finds those clusters in a single run, where hand-written reductions find one at
a time.

Each cell is a whole standalone program that prints the payload, round-tripped
through the carrier. Run it on both backends and diff: the interpreter is the
reference (CLAUDE.md), so a cell where native disagrees with interp is a native
bug, and a cell where both fail the same way is usually unimplemented.

Usage:
    python3 tests/matrix/gen.py <outdir>          # write every cell
    python3 tests/matrix/gen.py <outdir> --types f32,f64
    python3 tests/matrix/gen.py --list            # print the cell names

tests/matrix/run.sh drives generation + both backends + the diff.
"""

import argparse
import os
import sys

# ── Payload types ────────────────────────────────────────────────
# `decl` is the type as written in Rask, `val`/`val2` two distinct literals,
# `show` the expected stdout for `val`. Keep the literals printable exactly:
# a cell must fail on a wrong value, not on float formatting.
TYPES = {
    "i64":    dict(decl="i64",    val="42",              val2="7",     show="42"),
    "i32":    dict(decl="i32",    val="42",              val2="7",     show="42"),
    "u8":     dict(decl="u8",     val="200",             val2="7",     show="200"),
    "u64":    dict(decl="u64",    val="42",              val2="7",     show="42"),
    "f64":    dict(decl="f64",    val="2.5",             val2="1.5",   show="2.5"),
    "f32":    dict(decl="f32",    val="2.5",             val2="1.5",   show="2.5"),
    "bool":   dict(decl="bool",   val="true",            val2="false", show="true"),
    "string": dict(decl="string", val="\"hi\"",          val2="\"yo\"", show="hi"),
    "struct": dict(decl="Pay",    val="Pay { a: 42 }",   val2="Pay { a: 7 }",
                   show="Pay(42)", field=".a", field_show="42"),
    "enum":   dict(decl="Colour", val="Colour.Red",      val2="Colour.Blue",
                   show="Red"),
}

PRELUDE = """\
// SPDX-License-Identifier: (MIT OR Apache-2.0)
// GENERATED by tests/matrix/gen.py — do not edit by hand.
struct Pay {
    a: i64
}

enum Colour {
    Red
    Blue
}

extend Colour {
    func name(self) -> string {
        match self {
            Colour.Red => { return "Red" }
            Colour.Blue => { return "Blue" }
        }
    }
}
"""


def show_expr(t, expr):
    """How to render a payload of type `t` held in `expr`, as a string interp."""
    if t == "struct":
        return "Pay({%s.a})" % expr
    if t == "enum":
        return "{%s.name()}" % expr
    return "{%s}" % expr


# ── Carriers ─────────────────────────────────────────────────────
# Each builds the body of `main` (or extra decls + body) for one payload type.
# Every cell prints exactly one line: `got=<rendered payload>`.


def c_local(t, ty):
    return "", """\
    let x: {decl} = {val}
    println("got={show}")
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "x"))


def c_param_return(t, ty):
    decls = """\
func roundtrip(x: {decl}) -> {decl} {{
    return x
}}
""".format(decl=ty["decl"])
    return decls, """\
    let x: {decl} = {val}
    let y = roundtrip(x)
    println("got={show}")
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "y"))


def c_optional(t, ty):
    return "", """\
    let o: {decl}? = {val}
    if o? as v {{
        println("got={show}")
    }} else {{
        println("got=NONE")
    }}
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "v"))


def c_optional_param(t, ty):
    decls = """\
func unwrap_it(o: {decl}?) -> {decl} {{
    if o? as v {{
        return v
    }}
    return {val2}
}}
""".format(decl=ty["decl"], val2=ty["val2"])
    return decls, """\
    let o: {decl}? = {val}
    let v = unwrap_it(o)
    println("got={show}")
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "v"))


def c_result(t, ty):
    # An error type needs a `message` method — a primitive won't do (type.errors/ER4),
    # and Result is read with `catch`, not an `Ok`/`Err` pattern (ER2).
    decls = """\
enum Oops {{
    Bad
}}

extend Oops {{
    func message(self) -> string {{
        return "bad"
    }}
}}

func make() -> {decl} or Oops {{
    return {val}
}}
""".format(decl=ty["decl"], val=ty["val"])
    return decls, """\
    let v = make() catch _ => return
    println("got={show}")
""".format(show=show_expr(t, "v"))


def c_struct_field(t, ty):
    decls = """\
struct Holder {{
    inner: {decl}
}}
""".format(decl=ty["decl"])
    return decls, """\
    let h = Holder {{ inner: {val} }}
    println("got={show}")
""".format(val=ty["val"], show=show_expr(t, "h.inner"))


def c_vec_index(t, ty):
    return "", """\
    mut v: Vec<{decl}> = Vec.new()
    v.push({val2})
    v.push({val})
    println("got={show}")
""".format(decl=ty["decl"], val=ty["val"], val2=ty["val2"], show=show_expr(t, "v[1]"))


def c_map_value(t, ty):
    return "", """\
    mut m: Map<string, {decl}> = Map.new()
    m.insert("k", {val})
    if m.get("k")? as v {{
        println("got={show}")
    }} else {{
        println("got=MISSING")
    }}
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "v"))


def c_tuple(t, ty):
    return "", """\
    let tup = ({val2}, {val})
    println("got={show}")
""".format(val=ty["val"], val2=ty["val2"], show=show_expr(t, "tup.1"))


def c_closure_capture(t, ty):
    return "", """\
    let x: {decl} = {val}
    let f = || {{
        return x
    }}
    let y = f()
    println("got={show}")
""".format(decl=ty["decl"], val=ty["val"], show=show_expr(t, "y"))


CARRIERS = {
    "local":         c_local,
    "param_return":  c_param_return,
    "optional":      c_optional,
    "optional_param": c_optional_param,
    "result":        c_result,
    "struct_field":  c_struct_field,
    "vec_index":     c_vec_index,
    "map_value":     c_map_value,
    "tuple":         c_tuple,
    "closure":       c_closure_capture,
}


def expected(t):
    """The single line a correct cell prints."""
    ty = TYPES[t]
    if t == "struct":
        return "got=Pay(42)"
    if t == "enum":
        return "got=Red"
    return "got=" + ty["show"]


def cell(t, c):
    ty = TYPES[t]
    decls, body = CARRIERS[c](t, ty)
    return "{prelude}{decls}\nfunc main() {{\n{body}}}\n".format(
        prelude=PRELUDE, decls=decls, body=body
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir", nargs="?")
    ap.add_argument("--types", help="comma-separated payload types (default all)")
    ap.add_argument("--carriers", help="comma-separated carriers (default all)")
    ap.add_argument("--list", action="store_true", help="print cell names and exit")
    args = ap.parse_args()

    types = args.types.split(",") if args.types else list(TYPES)
    carriers = args.carriers.split(",") if args.carriers else list(CARRIERS)
    for t in types:
        if t not in TYPES:
            sys.exit("unknown payload type: %s (have %s)" % (t, ", ".join(TYPES)))
    for c in carriers:
        if c not in CARRIERS:
            sys.exit("unknown carrier: %s (have %s)" % (c, ", ".join(CARRIERS)))

    if args.list:
        for t in types:
            for c in carriers:
                print("%s__%s" % (c, t))
        return

    if not args.outdir:
        sys.exit("outdir required (or pass --list)")
    os.makedirs(args.outdir, exist_ok=True)
    n = 0
    for t in types:
        for c in carriers:
            name = "%s__%s" % (c, t)
            with open(os.path.join(args.outdir, name + ".rk"), "w") as f:
                f.write(cell(t, c))
            with open(os.path.join(args.outdir, name + ".expected"), "w") as f:
                f.write(expected(t) + "\n")
            n += 1
    print("wrote %d cells to %s" % (n, args.outdir))


if __name__ == "__main__":
    main()
